title: "Arden Photography"
description: test
author: "Cam Arden"
description: "Cam Arden Photography 2023 | All Rights Reserved"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {title: "Environmental Portraits", file: "enviroport.md"}
  - {title: "UVIVF", file: "uvivf.md"}
  - {file: "README.md"}
  - {title: "Ortho Maps", url: "https://camarden.github.io/qgis2web_2025_01_04-17_51_26_600223/#19/-38.29134/145.17351"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
   - {title: Contact, icon: envelope, url: "ardencameron@gmail.com", file: "contactme.md", permalink: "/contactme.md"}
  # - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
